spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: L67czc6aZ5wcRBzi
    username: waibao_service
    url: jdbc:mysql://1.12.48.159:3306/waibao_service?useSSL=false&amp;useServerPrepStmts=true

mybatis:
  config-location: mybatis/mybatis-config.xml
  mapper-locations: com/waibaoservice/mapper/*.xml
  type-aliases-package: com.waibaoservice.pojo